routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/saludo', function () {
    return 'Cielos nena, estas haciendo pollo frito?';
});

//Ruta de recursos GET POST PUT DELETE
Route::resource('/pokemones', 
App\Http\Controllers\PokemonController::class);

//Ruta normal
//Route::get('/pokemones', 
//[App\Http\Controllers\PokemonController::class,'index']);

app/Models/Pokemon.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Pokemon extends Model
{
    use HasFactory;
    protected $fillable = ['nombre','tipo','habilidades','pokedex'];
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

app/Http/Controllers/PokemonController.php
<?php

namespace App\Http\Controllers;

use App\Models\Pokemon;
use Illuminate\Http\Request;

class PokemonController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $pokemones = Pokemon::all();
        return view('pokevista',compact('pokemones'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('crear');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $request->validate([
            'nombre' => 'required',
            'tipo' => 'required',
            'habilidades' => 'required',
            'pokedex' => 'required|numeric'
        ]);

        $pokemon = new Pokemon($request->input());
        $pokemon->save();
        return redirect()->route('pokemones.index')
        ->with('success','Pokemon en su pokebola');
    }

    /**
     * Display the specified resource.
     */
    public function show(Pokemon $pokemon)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit($id)
    {
        $pokemon = Pokemon::find($id);
        return view('editar',compact('pokemon'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'nombre' => 'required',
            'tipo' => 'required',
            'habilidades' => 'required',
            'pokedex' => 'required|numeric'
        ]);
        
        $pokemon = Pokemon::find($id);
        $pokemon->update($request->input());
        return redirect()->route('pokemones.index')
        ->with('success','Pokemon Actualizado');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy($id)
    {
        $pokemon = Pokemon::find($id);
        $pokemon->delete();
        return redirect()->route('pokemones.index')
        ->with('success','Pokemon Eliminado');
    }
}

resources/views/crear.blade.php
@extends('formulario')
@section('form')
   Crear
 @endsection
@section('action')
action="{{route('pokemones.store' )}}"
@endsection

resources/views/editar.blade.php
@extends('formulario')
@section('form') 
 -Editar
 @endsection
 @section('action')
 action="{{route('pokemones.update',$pokemon->id )}}"
@endsection
@section('metodo')
    @method('PUT')
@endsection

resources/views/formulario.blade.php
@extends('plantilla')
@section('titulo')
-@yield('form')
 @endsection
 @section('principal')
 @if($errors->any())
 <div class="row">
  <div class="col-md-6 offset-md-3">
    <div class="alert alert-danger">
      <ul>
      @foreach($errors->all() as $e)
      <li> {{ $e }}</li>     
      @endforeach
@endif
      </ul>
    </div>
  </div>
 </div>
 <div class="row">
    <div class="col">
        <div class="card">
            <div class="card-header">@yield('form')</div>
                <div class="card-body">
                    <form method="POST" @yield('action')>
                        @csrf
                        @yield('metodo')
                        <div class="input-group mb-3">
                            <span class="input-group-text">@</span>
                            <input name="nombre" type="text" class="form-control" placeholder="Nombre" @isset($pokemon) value="{{$pokemon->nombre}}" @endisset>
                          </div>
                          <div class="input-group mb-3">
                            <span class="input-group-text">@</span>
                            <input name="tipo" type="text" class="form-control" placeholder="Tipo" @isset($pokemon) value="{{$pokemon->tipo}}" @endisset>>
                          </div>
                          <div class="input-group mb-3">
                            <span class="input-group-text">@</span>
                            <input name="habilidades" type="text" class="form-control" placeholder="Habilidades" @isset($pokemon) value="{{$pokemon->habilidades}}" @endisset>>
                          </div>
                          <div class="input-group mb-3">
                            <span class="input-group-text">@</span>
                            <input name="pokedex" type="text" class="form-control" placeholder="Pokedex" @isset($pokemon) value="{{$pokemon->pokedex}}" @endisset>>
                          </div>
                          <button class="btn btn-success">Enviar</button>
                    </form>
                </div>
        </div>
    </div>
 </div>
 @endsection

resources/views/plantilla.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Pokemones @yield('titulo')</title>
    @vite(['resources/css/app.css', 'resources/js/app.js'])
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-danger bg-warning">
        <div class="container-fluid">
          <a class="navbar-brand" >Pokemones</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{{ route('pokemones.index')}}">Listado</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ route('pokemones.create')}}">Crear</a>
              </li>    
            </ul>
          </div>
        </div>
      </nav>
    <div class="containier mt-3">
        @yield('principal')
    </div>
</body>
@yield('js')
</html>

resources/views/pokevista.blade.php
@extends('plantilla')
@section('titulo')
    -Listado
@endsection
@section('principal')
@if($mensaje = Session::get('success'))
<div class="row" id="divok">
    <div class="col-md-6 offset-md-3">
        <div class="alert alert-success">
            {{$mensaje}}
        </div>
    </div>
</div>
@endif
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="table-responsive">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>NOMBRE</th>
                                <th>TIPO</th>
                                <th>HABILIDADES</th>
                                <th>POKEDEX</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($pokemones as $i => $row)
                                <tr>
                                    <td>{{($i+1)}}</td>
                                    <td>{{$row->nombre}}</td>
                                    <td>{{$row->tipo}}</td>
                                    <td>{{$row->habilidades}}</td>
                                    <td>{{$row->pokedex}}</td>
                                    <td>
                                        <a class="btn btn-success" href="{{ route('pokemones.edit',$row->id)}}">
                                            <i class="fa-solid fa-edit"></i>
                                        </a>
                                    </td>
                                    <td>
                                        <form method="POST" id="frm_{{$row->id}}" action="{{route('pokemones.destroy',$row->id)}}">
                                            @csrf
                                            @method('DELETE')
                                            <button  class="btn btn-danger" onclick="datos('{{$row->id}}','{{$row->nombre}}')" type="button" data-bs-toggle="modal" data-bs-target="#modalEliminar"><i class="fa-solid fa-trash"></i></button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="modal" tabindex="-1" id="modalEliminar">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title">Eliminar</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              <p>¿Seguro Que Quieres Elimar El Pokemon #<label id="lbl_nombre"></label>?</p>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal"><i class="fa-solid fa-ban"></i> Ñao Ñao</button>
              <button id="btnEliminar" type="button" class="btn btn-success"><i class="fa-solid fa-check"></i> Si, pokeliminalo</button>
            </div>
          </div>
        </div>
      </div>
@endsection
@section('js')
@vite('resources/js/listado.js')
@endsection